//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.DEPARTMENTS = new HashSet<DEPARTMENT>();
            this.EMPLOYEES1 = new HashSet<EMPLOYEE>();
            this.JOB_HISTORY = new HashSet<JOB_HISTORY>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE_NUMBER { get; set; }
        public System.DateTime HIRE_DATE { get; set; }
        public string JOB_ID { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> COMMISSION_PCT { get; set; }
        public Nullable<int> MANAGER_ID { get; set; }
        public Nullable<short> DEPARTMENT_ID { get; set; }
    
        public virtual ICollection<DEPARTMENT> DEPARTMENTS { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual JOB JOB { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEES1 { get; set; }
        public virtual EMPLOYEE EMPLOYEE1 { get; set; }
        public virtual ICollection<JOB_HISTORY> JOB_HISTORY { get; set; }
    }
}
