//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.COUNTRIES = new HashSet<COUNTRy>();
        }
    
        public decimal REGION_ID { get; set; }
        public string REGION_NAME { get; set; }
    
        public virtual ICollection<COUNTRy> COUNTRIES { get; set; }
    }
}
